import { useEffect, useState, useRef } from 'react';
import { Card, Typography, Spin, Row, Col, Tag, Table, Statistic, Divider, Button, Space, Alert, Empty } from 'antd';
import { DownloadOutlined, PrinterOutlined, CheckCircleOutlined, ThunderboltOutlined, FileTextOutlined } from '@ant-design/icons';
import { useIndustryStore } from '../store/industryStore';
import { useLocaleStore } from '../store/localeStore';
import { getIndustryReport } from '../services/api';

const { Title, Paragraph, Text } = Typography;

const moduleColors: Record<string, string> = {
  doc_parser: '#1677ff', demand_forecast: '#52c41a', ai_agent: '#722ed1',
  risk_control: '#fa8c16', chatbi: '#13c2c2',
};
const moduleNames: Record<string, string> = {
  doc_parser: 'Doc Parser', demand_forecast: 'Forecast', ai_agent: 'AI Agent',
  risk_control: 'Risk Control', chatbi: 'ChatBI',
};
const moduleIcons: Record<string, any> = {
  doc_parser: <FileTextOutlined />, demand_forecast: <ThunderboltOutlined />, ai_agent: <ThunderboltOutlined />,
  risk_control: <ThunderboltOutlined />, chatbi: <ThunderboltOutlined />,
};

export default function ReportPreview() {
  const { currentId, currentData } = useIndustryStore();
  const { t, locale } = useLocaleStore();
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setLoading(true);
    getIndustryReport().then(res => {
      setReport(res.report || null);
    }).catch(() => {
      setReport(null);
    }).finally(() => setLoading(false));
  }, [currentData]);

  const handlePrint = () => {
    const win = window.open('', '_blank');
    if (!win) return;
    const style = document.querySelector('style')?.innerHTML || '';
    const content = reportRef.current?.innerHTML || '';
    const pageTitle = `${report?.industry_name || ''} ${t('report.title')}`;
    win.document.write(`<!DOCTYPE html><html><head><title>${pageTitle}</title>
      <style>body{font-family:'SimSun','Microsoft YaHei',serif;padding:40px;color:#333;max-width:900px;margin:auto}
      h1{text-align:center;font-size:24px;border-bottom:2px solid #1677ff;padding-bottom:12px}
      h2{font-size:18px;color:#1677ff;margin-top:28px;border-left:4px solid #1677ff;padding-left:12px}
      h3{font-size:15px;margin-top:16px;color:#333}
      table{width:100%;border-collapse:collapse;margin:12px 0}
      th,td{border:1px solid #ddd;padding:8px 12px;text-align:left;font-size:13px}
      th{background:#f5f5f5;font-weight:600}
      .roi-box{background:#f6ffed;border:1px solid #b7eb8f;padding:16px;border-radius:8px;margin:16px 0}
      .pain{background:#fff2f0;border:1px solid #ffccc7;padding:12px;border-radius:6px;margin:8px 0}
      .sol{background:#f6ffed;border:1px solid #b7eb8f;padding:12px;border-radius:6px;margin:8px 0}
      .footer{text-align:center;color:#999;font-size:12px;margin-top:40px;border-top:1px solid #eee;padding-top:16px}
      .tag{display:inline-block;padding:2px 10px;border-radius:4px;font-size:12px;color:#fff;margin-right:6px}
      .metric-box{display:inline-block;width:30%;margin:8px;padding:12px;background:#fafafa;border-radius:6px;text-align:center}
      @media print{body{padding:20px}.no-print{display:none!important}}
      </style></head><body>
      <div class="no-print" style="text-align:right;margin-bottom:20px">
        <button onclick="window.print()" style="padding:8px 24px;background:#1677ff;color:#fff;border:none;border-radius:4px;cursor:pointer;font-size:14px">🖨️ ${t('report.printOrPDF')}</button>
      </div>
      ${content}
      <div class="footer">Enterprise AI Hub · ${t('report.autoGenerated')} | ${report?.industry_name || ''} ${t('report.title')} | ${new Date().toLocaleDateString()}</div>
    </body></html>`);
    win.document.close();
  };

  if (loading && !report) return <Spin size="large" style={{ display: 'block', paddingTop: 120, textAlign: 'center' }} />;
  if (!report) return <Empty description={locale === 'zh' ? '暂无报告数据' : 'No report data'} style={{ paddingTop: 80 }} />;

  const painPoints = report.pain_points || [];
  const solutions = report.solutions || [];
  const roi = report.roi_data || {};
  const metrics = roi.metrics || [];

  const roiColumns = [
    { title: locale === 'zh' ? '维度' : 'Category', dataIndex: 'category', key: 'category' },
    { title: locale === 'zh' ? '节省金额' : 'Amount', dataIndex: 'amount', key: 'amount', render: (v: string) => <Text strong style={{ color: '#52c41a' }}>{v}</Text> },
    { title: locale === 'zh' ? '说明' : 'Detail', dataIndex: 'detail', key: 'detail', ellipsis: true },
  ];

  return (
    <div>
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <Title level={3} style={{ margin: 0 }}>{report.icon || '📋'} {report.industry_name} · {t('report.title')}</Title>
          <Paragraph type="secondary" style={{ margin: '4px 0 0' }}>{t('report.painPoints')} · {t('report.solutions')} · ROI · {t('report.exportPDF')}</Paragraph>
        </div>
        <Space>
          <Button icon={<PrinterOutlined />} onClick={handlePrint}>{t('report.print')} / PDF</Button>
        </Space>
      </div>

      {/* ===== PDF Report Preview ===== */}
      <div ref={reportRef} style={{ maxWidth: 900, margin: '0 auto', padding: '24px 0' }}>

        {/* Header */}
        <div style={{ textAlign: 'center', borderBottom: '2px solid #1677ff', paddingBottom: 16, marginBottom: 24 }}>
          <Title level={2} style={{ margin: 0 }}>Enterprise AI Hub</Title>
          <Title level={4} type="secondary" style={{ margin: '8px 0 0' }}>
            {report.industry_name} · {t('report.title')}
          </Title>
          <Text type="secondary">{locale === 'zh' ? '生成日期' : 'Date'}: {new Date().toLocaleDateString()} | v2.0.0</Text>
        </div>

        {/* Executive Summary */}
        <Card size="small" style={{ marginBottom: 20, background: '#f0f5ff', border: '1px solid #d6e4ff' }}>
          <Space>
            <CheckCircleOutlined style={{ fontSize: 24, color: '#1677ff' }} />
            <div>
              <Text strong style={{ fontSize: 15 }}>{t('report.executiveSummary')}</Text>
              <Paragraph style={{ margin: '4px 0 0', fontSize: 13 }}>
                {locale === 'zh'
                  ? `${report.industry_name}企业通过部署Enterprise AI Hub中台，一次性解决5大模块痛点。年投资${roi.total_investment}，带来年化收益${roi.annual_savings}，ROI达`
                  : `By deploying Enterprise AI Hub, the ${report.industry_name_en || report.industry_name} company solves 5 module pain points at once. Annual investment: ${roi.total_investment}, savings: ${roi.annual_savings}, ROI:`}
                <Text strong style={{ color: '#52c41a', fontSize: 16 }}>{roi.roi_percent}%</Text>，
                <Text strong>{roi.payback_months}{locale === 'zh' ? '个月' : ' months'}</Text>{locale === 'zh' ? '收回投资。' : ' payback period.'}
              </Paragraph>
            </div>
          </Space>
        </Card>

        {/* ROI KPI Cards */}
        <Row gutter={12} style={{ marginBottom: 20 }}>
          {[
            { label: locale === 'zh' ? '年投资额' : 'Investment', value: roi.total_investment, color: '#1677ff' },
            { label: locale === 'zh' ? '年化节省' : 'Savings', value: roi.annual_savings, color: '#52c41a' },
            { label: locale === 'zh' ? '投资回报率' : 'ROI', value: `${roi.roi_percent}%`, color: '#722ed1' },
            { label: locale === 'zh' ? '回本周期' : 'Payback', value: roi.payback_months + (locale === 'zh' ? '个月' : ' months'), color: '#fa8c16' },
          ].map((kpi, i) => (
            <Col span={6} key={i}>
              <Card size="small" className="kpi-card" style={{ textAlign: 'center' }}>
                <Statistic title={kpi.label} value={kpi.value} valueStyle={{ color: kpi.color, fontSize: 22 }} />
              </Card>
            </Col>
          ))}
        </Row>

        {/* Section 1: Pain Points */}
        <div style={{ marginBottom: 24 }}>
          <Title level={4} style={{ borderLeft: '4px solid #ff4d4f', paddingLeft: 12, color: '#ff4d4f' }}>
            {locale === 'zh' ? '一、行业痛点分析' : '1. Pain Points'}
          </Title>
          {painPoints.map((p: any, i: number) => (
            <div key={i} style={{ background: '#fff2f0', border: '1px solid #ffccc7', borderRadius: 6, padding: '12px 16px', marginBottom: 8 }}>
              <Space>
                <Tag color={moduleColors[p.module]}>{moduleNames[p.module] || p.module}</Tag>
                <Text strong>{p.title}</Text>
              </Space>
              <Paragraph style={{ margin: '6px 0 0', fontSize: 13, color: '#555' }}>{p.desc}</Paragraph>
            </div>
          ))}
        </div>

        {/* Section 2: AI Solutions */}
        <div style={{ marginBottom: 24 }}>
          <Title level={4} style={{ borderLeft: '4px solid #52c41a', paddingLeft: 12, color: '#52c41a' }}>
            {locale === 'zh' ? '二、AI解决方案' : '2. AI Solutions'}
          </Title>
          {solutions.map((s: any, i: number) => (
            <div key={i} style={{ background: '#f6ffed', border: '1px solid #b7eb8f', borderRadius: 6, padding: '12px 16px', marginBottom: 8 }}>
              <Space>
                <Tag color={moduleColors[s.module]}>{moduleNames[s.module] || s.module}</Tag>
                <Text strong>{s.title}</Text>
              </Space>
              <Paragraph style={{ margin: '6px 0 0', fontSize: 13, color: '#555' }}>{s.desc}</Paragraph>
            </div>
          ))}
        </div>

        {/* Section 3: Before vs After Metrics */}
        <div style={{ marginBottom: 24 }}>
          <Title level={4} style={{ borderLeft: '4px solid #1677ff', paddingLeft: 12, color: '#1677ff' }}>
            {locale === 'zh' ? '三、实施前后对比' : '3. Before vs After'}
          </Title>
          <Row gutter={[8, 8]}>
            {metrics.map((m: any, i: number) => (
              <Col span={8} key={i}>
                <Card size="small" style={{ textAlign: 'center', background: '#fafafa' }}>
                  <Text style={{ fontSize: 12, color: '#666' }}>{m.label}</Text>
                  <div style={{ margin: '4px 0' }}>
                    <Text delete type="secondary" style={{ fontSize: 12 }}>{m.before}</Text>
                    <Text strong style={{ color: '#1677ff', fontSize: 18, margin: '0 8px' }}>{m.after}</Text>
                  </div>
                  <Tag color="green" style={{ fontSize: 12 }}>{m.improvement}</Tag>
                </Card>
              </Col>
            ))}
          </Row>
        </div>

        {/* Section 4: ROI Breakdown */}
        <div style={{ marginBottom: 24 }}>
          <Title level={4} style={{ borderLeft: '4px solid #fa8c16', paddingLeft: 12, color: '#fa8c16' }}>
            {locale === 'zh' ? '四、年度效益分解' : '4. Annual Breakdown'}
          </Title>
          <Table
            dataSource={roi.annual_breakdown || []}
            columns={roiColumns}
            pagination={false}
            size="small"
            bordered
            summary={() => (
              <Table.Summary.Row>
                <Table.Summary.Cell index={0}><Text strong>{locale === 'zh' ? '合计' : 'Total'}</Text></Table.Summary.Cell>
                <Table.Summary.Cell index={1}><Text strong style={{ color: '#52c41a' }}>{roi.annual_savings}</Text></Table.Summary.Cell>
                <Table.Summary.Cell index={2}><Text strong>ROI {roi.roi_percent}% · {roi.payback_months}{locale === 'zh' ? '个月回本' : ' months payback'}</Text></Table.Summary.Cell>
              </Table.Summary.Row>
            )}
          />
        </div>

        {/* Section 5: Summary */}
        <Alert
          type="success"
          showIcon
          message={t('report.summary')}
          description={t('report.summaryText', {
            industry: report.industry_name,
            investment: roi.total_investment,
            savings: roi.annual_savings,
            roi: String(roi.roi_percent),
            payback: String(roi.payback_months),
          })}
          style={{ marginBottom: 24 }}
        />

        {/* Footer */}
        <div style={{ textAlign: 'center', color: '#999', fontSize: 12, borderTop: '1px solid #eee', paddingTop: 16 }}>
          {t('report.footer')}
        </div>
      </div>

      {/* Print Hint */}
      <div style={{ textAlign: 'center', margin: '16px 0 40px' }}>
        <Button type="primary" icon={<PrinterOutlined />} size="large" onClick={handlePrint}>
          {t('report.print')} / PDF
        </Button>
        <Text type="secondary" style={{ display: 'block', marginTop: 8, fontSize: 12 }}>
          {t('report.printHint')}
        </Text>
      </div>
    </div>
  );
}
